api_platform:
    title: 'Terra Nutri API'
    description: 'The Terra Nutri API enables external systems to connect with and transfer information'
    version: 1.0.0
    show_webby: false
    formats:
        json: [ 'application/json' ]
        jsonld: ['application/ld+json']
        html: [ 'text/html' ]
        multipart: [ 'multipart/form-data' ]
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    patch_formats:
        json: ['application/merge-patch+json']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false

    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
    enable_swagger_ui: false
    enable_re_doc: false
    openapi:
        contact:
            name: Terra Nutrition & Health
            url: https://www.terranutri.net
            email: igorjacon90@gmail.com
