when@prod:
    framework:
        mailer:
            dsn: '%env(MAILER_DSN)%'
            envelope:
                recipients:
                    - igorjacon90@gmail.com
                    - r.hollis.10@student.scu.edu.au
                    - m.waheed.12@student.scu.edu.au
                    - d.champion.10@student.scu.edu.au

when@dev:
    framework:
        mailer:
            dsn: '%env(MAILER_DSN)%'
            envelope:
                recipients: ['%supportEmail%']
