when@prod:
    framework:
        mailer:
            dsn: '%env(MAILER_DSN)%'

when@dev:
    framework:
        mailer:
            dsn: '%env(MAILER_DSN)%'
            envelope:
                recipients: ['%supportEmail%']
