twig:
    paths: ['%kernel.project_dir%/templates']
    file_name_pattern: '*.twig'

    globals:
        locales: "%locales%"
        domain: "%domain%"
        supportEmail: '%supportEmail%'

when@test:
    twig:
        strict_variables: true
