twig:
    paths: ['%kernel.project_dir%/templates']
    file_name_pattern: '*.twig'

    form_themes:
        - '_form/layout.html.twig'
        - '_form/fields.html.twig'
        - '_form/vertical_fields.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    globals:
        settings_manager: '@App\Manager\SiteSettingsManager'
        customer_manager: '@App\Manager\CustomerManager'
        locales: "%locales%"
        domain: "%domain%"
        supportEmail: '%supportEmail%'

when@test:
    twig:
        strict_variables: true
