vich_uploader:
  db_driver: orm

  mappings:
    system_files:
      namer: Vich\UploaderBundle\Naming\OrignameNamer
      uri_prefix: /uploads/settings
      upload_destination: '%kernel.project_dir%/public/uploads/settings'
    user_files:
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      uri_prefix: /uploads/user
      upload_destination: '%kernel.project_dir%/public/uploads/user'