vich_uploader:
  db_driver: orm

  mappings:
    system_files:
      namer: Vich\UploaderBundle\Naming\OrignameNamer
      uri_prefix: /uploads/settings
      upload_destination: '%kernel.project_dir%/public/uploads/settings'
    professional_files:
      namer: Vich\UploaderBundle\Naming\OrignameNamer
      uri_prefix: /uploads/professionals
      upload_destination: '%kernel.project_dir%/public/uploads/professionals'
      directory_namer:
        service: vich_uploader.namer_directory_property
        options: { property: 'user.id' }